// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pHEc37smer1Q6xynjofQze
// Component: X8W6uPQ1iv-Hk
import * as React from "react";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: Tv1TEamQVURUK/component
import Button from "../../Button"; // plasmic-import: oB--Goin9nXSTb/component
import ProductCard from "../../ProductCard"; // plasmic-import: -LfFeyZiOYdDxo/component
import Ratings from "../../Ratings"; // plasmic-import: IuSNyP1i29NJld/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: zao5vJN0LZKBgA/component
import BlogPost from "../../BlogPost"; // plasmic-import: jeBG2EE2oYolA-/component
import Footer from "../../Footer"; // plasmic-import: B_rjbW1b21_BN/component
import ProductRow from "../../ProductRow"; // plasmic-import: bLfbJFXqGo9g4o/component
import { useScreenVariants as useScreenVariantsv5FSi0UE2M7YwV } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: V5fSI0uE2M7ywV/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_planty.module.css"; // plasmic-import: pHEc37smer1Q6xynjofQze/projectcss
import sty from "./PlasmicHome.module.css"; // plasmic-import: X8W6uPQ1iv-Hk/css
import ButtonArrowIcon from "./icons/PlasmicIcon__ButtonArrow"; // plasmic-import: jlA16urbNwYxya/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: zEbPE1di54zoFB/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: akpqReMOnsG-aF/icon
import QuotessvgIcon from "./icons/PlasmicIcon__Quotessvg"; // plasmic-import: UCjD1tfFI5j0sC/icon

export const PlasmicHome__VariantProps = new Array();

export const PlasmicHome__ArgProps = new Array();

function PlasmicHome__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsv5FSi0UE2M7YwV()
  });

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__kDrOc)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__ooJsk)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__twXS)}>
                <Header
                  className={classNames("__wab_instance", sty.header__k3DuR)}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__npUow)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"Real, beautiful plants \nright to your door"}
                  </h1>

                  <Button
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames("__wab_instance", sty.button)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__woDb2
                      )}
                    >
                      {"See all plants"}
                    </div>

                    <ButtonArrowIcon
                      className={classNames(projectcss.all, sty.svg___4Je)}
                      role={"img"}
                    />
                  </Button>
                </p.Stack>
              </div>
            </p.Stack>

            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__sQczf)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__ptLFs
                  )}
                >
                  {"Top Collections"}
                </h2>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns___11Wel)}
              >
                <div className={classNames(projectcss.all, sty.column__oc5PD)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__uRf73
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__dqvM)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: "/plasmic/planty/images/galinaNMiziNqvJx5MUnsplashjpg.jpeg",
                          fullWidth: 1920,
                          fullHeight: 1278,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$65.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__lqas3
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__a2BIx)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__qwy0W
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__zIt)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: "/plasmic/planty/images/igorSonFvPxCqgtwcUnsplashjpg.jpeg",
                          fullWidth: 640,
                          fullHeight: 481,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$80.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__mpEy3
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__dE6Q)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__jwnWn
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__ih3Tb)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: "/plasmic/planty/images/scottWebbORwRlTgBrPoUnsplashjpg.jpeg",
                          fullWidth: 1920,
                          fullHeight: 1280,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$40.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings___613RE
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column___34Oz3)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__oz8Xs
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__aBrau)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: "/plasmic/planty/images/freddieMarriageUcfKyTanLuUnsplashjpg.jpeg",
                          fullWidth: 640,
                          fullHeight: 427,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$100.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__h5Jof
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <FeatureItem
                data-plasmic-name={"featureItem"}
                data-plasmic-override={overrides.featureItem}
                className={classNames("__wab_instance", sty.featureItem)}
              />
            ) : null}
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__bAwpQ)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1KkLi
                  )}
                >
                  {"Featured Products"}
                </div>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__ngdR2)}
              >
                <div className={classNames(projectcss.all, sty.column__h2X8E)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__fVsZ2
                    )}
                    price={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mrhIj
                        )}
                      >
                        {"$160.00"}
                      </div>
                    }
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__l0Ddw
                        )}
                        numReviews={"(12 Review)"}
                        stars={"two"}
                      />
                    }
                    title={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__i878U
                        )}
                      >
                        {"Designed Sofa"}
                      </div>
                    }
                    withReviews={true}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__nUr0J)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard___3ZeLi
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__p9Sqv)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: "/plasmic/planty/images/f2.jpeg",
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$200.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__llona
                        )}
                        stars={"four"}
                      />
                    }
                    title={"Dining Table"}
                    withReviews={true}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column___0YsHu)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__wOy8Q
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__s8ZZb)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: "/plasmic/planty/images/f3.jpeg",
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$100.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__qwC8C
                        )}
                        numReviews={"(23 Review)"}
                        stars={"five"}
                      />
                    }
                    title={"Chair and Table"}
                    withReviews={true}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__s8Fht)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__lyz5Y
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__b7ICc)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: "/plasmic/planty/images/f4.jpeg",
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$299.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings___1CkMe
                        )}
                        numReviews={"(35 Review)"}
                      />
                    }
                    title={"Modern Arm Chair"}
                    withReviews={true}
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__hTFuP)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__l26U
                  )}
                >
                  {"Latest Blog"}
                </div>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__eor2K)}
              >
                <div className={classNames(projectcss.all, sty.column__ro7L)}>
                  <BlogPost
                    className={classNames(
                      "__wab_instance",
                      sty.blogPost___9DItV
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___9EQHg)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: "/plasmic/planty/images/b1.jpeg",
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__oEiY)}>
                  <BlogPost
                    className={classNames(
                      "__wab_instance",
                      sty.blogPost___4N3B4
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__jtL43)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: "/plasmic/planty/images/b2.jpeg",
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__zEp4)}>
                  <BlogPost
                    className={classNames(
                      "__wab_instance",
                      sty.blogPost__zkYnP
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___95Ki1)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: "/plasmic/planty/images/b3.jpeg",
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___8HhJ)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__sWkL)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"90px"}
                  src={{
                    src: "/plasmic/planty/images/adidas.png",
                    fullWidth: 90,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__bV7Z)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"91px"}
                  src={{
                    src: "/plasmic/planty/images/hm.png",
                    fullWidth: 91,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___6HOlx)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"98px"}
                  src={{
                    src: "/plasmic/planty/images/kappa.png",
                    fullWidth: 98,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__ho5Ak)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"124px"}
                  src={{
                    src: "/plasmic/planty/images/lacoste.png",
                    fullWidth: 124,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__fgFyh)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"125px"}
                  src={{
                    src: "/plasmic/planty/images/levis.png",
                    fullWidth: 125,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />
              </p.Stack>
            ) : null}
            {true ? (
              <Footer
                className={classNames("__wab_instance", sty.footer__irBQy)}
              />
            ) : null}
          </div>

          <p.Stack
            as={"div"}
            data-plasmic-name={"bestSellers"}
            data-plasmic-override={overrides.bestSellers}
            hasGap={true}
            className={classNames(projectcss.all, sty.bestSellers)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__bOoDq)}
              >
                <Icon2Icon
                  className={classNames(projectcss.all, sty.svg__ibL9N)}
                  role={"img"}
                />

                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__gJzMy
                  )}
                >
                  {"Best sellers"}
                </h2>
              </p.Stack>
            ) : null}
            {true ? (
              <ProductRow
                data-plasmic-name={"productRow"}
                data-plasmic-override={overrides.productRow}
                className={classNames("__wab_instance", sty.productRow)}
              />
            ) : null}
          </p.Stack>

          <p.Stack
            as={"div"}
            data-plasmic-name={"bigPlants"}
            data-plasmic-override={overrides.bigPlants}
            hasGap={true}
            className={classNames(projectcss.all, sty.bigPlants)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__x3Zgz)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__cgWoE
                  )}
                >
                  {"Big plants"}
                </h2>
              </p.Stack>
            ) : null}

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__x7BXr)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__gC5Vf)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__c7Up6)}
                  displayHeight={"270px /* plasmic-token: dSJ4iuMuCkBucj */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant6Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__pJujc)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__aBiP)}
                      role={"img"}
                    />
                  </div>
                ) : null}

                <div className={classNames(projectcss.all, sty.freeBox__lcQ4U)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__hcbp
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Donec finibus"}
                  </p.PlasmicLink>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xj6XK
                    )}
                  >
                    {"bigplants"}
                  </div>

                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__g09B
                    )}
                  >
                    {"$100.00"}
                  </h5>
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__mc4By)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__mskjP)}
                  displayHeight={"270px /* plasmic-token: dSJ4iuMuCkBucj */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant1Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ctHu)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__h7Ox4)}
                      role={"img"}
                    />
                  </div>
                ) : null}

                <div className={classNames(projectcss.all, sty.freeBox__z2Ocx)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__wckGz
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Nulla suscipit"}
                  </p.PlasmicLink>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__a07O3
                    )}
                  >
                    {"bigplants "}
                  </div>

                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___54Px
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___6Mx0K)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__hzuLa)}
                  displayHeight={"270px /* plasmic-token: dSJ4iuMuCkBucj */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant7Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__lq8MZ)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__dta0W)}
                      role={"img"}
                    />
                  </div>
                ) : null}

                <div
                  className={classNames(projectcss.all, sty.freeBox___13S1T)}
                >
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__tFjW5
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Sed consectetur"}
                  </p.PlasmicLink>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rl6P7
                    )}
                  >
                    {"bigplants "}
                  </div>

                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__lTd22
                    )}
                  >
                    {"$18.40 "}
                  </h5>
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__hXw3F)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__kInSx)}
                  displayHeight={"270px /* plasmic-token: dSJ4iuMuCkBucj */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant5Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__h6Om0)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__iTd4)}
                      role={"img"}
                    />
                  </div>
                ) : null}

                <div
                  className={classNames(projectcss.all, sty.freeBox___8XtJd)}
                >
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__vnqz4
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Vestibulum eget"}
                  </p.PlasmicLink>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lskf7
                    )}
                  >
                    {"bigplants "}
                  </div>

                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__ix5X6
                    )}
                  >
                    {"$220.40 "}
                  </h5>
                </div>
              </p.Stack>
            </p.Stack>
          </p.Stack>

          <p.Stack
            as={"div"}
            data-plasmic-name={"cactuses"}
            data-plasmic-override={overrides.cactuses}
            hasGap={true}
            className={classNames(projectcss.all, sty.cactuses)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__q0BWw)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2___4EtP
                  )}
                >
                  {"Cactuses"}
                </h2>
              </p.Stack>
            ) : null}

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__zzSSz)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__tWtmd)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__atuX7)}
                  displayHeight={"270px /* plasmic-token: dSJ4iuMuCkBucj */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant41Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox___6AiIm)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg___1J1J)}
                      role={"img"}
                    />
                  </div>
                ) : null}

                <div className={classNames(projectcss.all, sty.freeBox__bkKli)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__xlkVl
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Cras molestie"}
                  </p.PlasmicLink>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ibqaK
                    )}
                  >
                    {"cactuses "}
                  </div>

                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___2HzlI
                    )}
                  >
                    {"$24.99"}
                  </h5>
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__qj2Tx)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__ei1LS)}
                  displayHeight={"270px /* plasmic-token: dSJ4iuMuCkBucj */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant31Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__gpbSk)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__oFpvN)}
                      role={"img"}
                    />
                  </div>
                ) : null}

                <div className={classNames(projectcss.all, sty.freeBox__ytaCa)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__wdRiF
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Curabitur eu tempor"}
                  </p.PlasmicLink>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wl7GQ
                    )}
                  >
                    {"Cactuses"}
                  </div>

                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__i22Zn
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__r2YvM)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___3ZhWn)}
                  displayHeight={"270px /* plasmic-token: dSJ4iuMuCkBucj */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant9Webp.webp",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__h5Ty)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__hxwkw)}
                      role={"img"}
                    />
                  </div>
                ) : null}

                <div className={classNames(projectcss.all, sty.freeBox__xixQ)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__semwK
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Fusce sagittis"}
                  </p.PlasmicLink>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vmE0W
                    )}
                  >
                    {"Cactuses"}
                  </div>

                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__m5JRi
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___6H3)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__rt1Jg)}
                  displayHeight={"270px /* plasmic-token: dSJ4iuMuCkBucj */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant2Webp.webp",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__q1TxC)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__d4W8L)}
                      role={"img"}
                    />
                  </div>
                ) : null}

                <div className={classNames(projectcss.all, sty.freeBox__mRvs)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___7C77T
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Integer porta"}
                  </p.PlasmicLink>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sMYcd
                    )}
                  >
                    {"Cactuses"}
                  </div>

                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__lUgoR
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>
            </p.Stack>
          </p.Stack>

          <p.Stack
            as={"div"}
            data-plasmic-name={"testimonials"}
            data-plasmic-override={overrides.testimonials}
            hasGap={true}
            className={classNames(projectcss.all, sty.testimonials)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___5Gy5J)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__fiJzH
                  )}
                >
                  {"Testimonials"}
                </h2>
              </p.Stack>
            ) : null}

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__nRxof)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__oqP3U)}
              >
                <QuotessvgIcon
                  className={classNames(projectcss.all, sty.svg__rOdO8)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xULmT
                  )}
                >
                  {
                    "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                  }
                </div>

                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__fXeE3)}
                  >
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__o6Iim
                      )}
                    >
                      {"JOHN DOPE,"}
                    </h5>

                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__qk1Dc
                      )}
                    >
                      {" COLORADO, USA"}
                    </h5>
                  </p.Stack>
                ) : null}
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__loHk0)}
              >
                <QuotessvgIcon
                  className={classNames(projectcss.all, sty.svg__gtHsk)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__o2Zbr
                  )}
                >
                  {
                    "Well I'll be d*mned. These plants really ARE greener than any of my recruits."
                  }
                </div>

                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__vRmMe)}
                  >
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__pu9MB
                      )}
                    >
                      {"MAJOR PAYNE"}
                    </h5>

                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__iQsan
                      )}
                    >
                      {", VA, USA"}
                    </h5>
                  </p.Stack>
                ) : null}
              </p.Stack>
            </p.Stack>
          </p.Stack>

          <Footer className={classNames("__wab_instance", sty.footer__bNmgE)} />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "h1",
    "button",
    "featureItem",
    "bestSellers",
    "productRow",
    "bigPlants",
    "cactuses",
    "testimonials"
  ],

  h1: ["h1"],
  button: ["button"],
  featureItem: ["featureItem"],
  bestSellers: ["bestSellers", "productRow"],
  productRow: ["productRow"],
  bigPlants: ["bigPlants"],
  cactuses: ["cactuses"],
  testimonials: ["testimonials"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps
    });

    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h1: makeNodeComponent("h1"),
    button: makeNodeComponent("button"),
    featureItem: makeNodeComponent("featureItem"),
    bestSellers: makeNodeComponent("bestSellers"),
    productRow: makeNodeComponent("productRow"),
    bigPlants: makeNodeComponent("bigPlants"),
    cactuses: makeNodeComponent("cactuses"),
    testimonials: makeNodeComponent("testimonials"),
    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
