// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pHEc37smer1Q6xynjofQze
// Component: IuSNyP1i29NJld
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_planty.module.css"; // plasmic-import: pHEc37smer1Q6xynjofQze/projectcss
import sty from "./PlasmicRatings.module.css"; // plasmic-import: IuSNyP1i29NJld/css
import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: co9ngxYOO7yRqU/icon

export const PlasmicRatings__VariantProps = new Array("stars");

export const PlasmicRatings__ArgProps = new Array("numReviews");

function PlasmicRatings__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootstars_five]: hasVariant(variants, "stars", "five"),
          [sty.rootstars_four]: hasVariant(variants, "stars", "four"),
          [sty.rootstars_one]: hasVariant(variants, "stars", "one"),
          [sty.rootstars_three]: hasVariant(variants, "stars", "three"),
          [sty.rootstars_two]: hasVariant(variants, "stars", "two"),
          [sty.rootstars_zero]: hasVariant(variants, "stars", "zero")
        }
      )}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {(hasVariant(variants, "stars", "zero") ? true : true) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__ew7Qa, {
              [sty.svgstars_five__ew7QaDAe4Z]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_zero__ew7Qa8966U]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__skF4I, {
              [sty.svgstars_five__skF4IdAe4Z]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__skF4Iwlptu]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_one__skF4IuMy6R]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svgstars_three__skF4IgmHjh]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two__skF4ISmpEf]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svgstars_zero__skF4I8966U]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg___7JQwa, {
              [sty.svgstars_five___7JQwaDAe4Z]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four___7JQwawlptu]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_one___7JQwauMy6R]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svgstars_three___7JQwagmHjh]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two___7JQwaSmpEf]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svgstars_zero___7JQwa8966U]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__nlsIn, {
              [sty.svgstars_five__nlsInDAe4Z]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__nlsInwlptu]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_one__nlsInuMy6R]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svgstars_three__nlsIngmHjh]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two__nlsInSmpEf]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svgstars_zero__nlsIn8966U]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg___9Q5Cd, {
              [sty.svgstars_five___9Q5CdDAe4Z]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four___9Q5Cdwlptu]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_one___9Q5CduMy6R]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svgstars_three___9Q5CdgmHjh]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two___9Q5CdSmpEf]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svgstars_zero___9Q5Cd8966U]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__bjKaC, {
              [sty.svgstars_five__bjKaCdAe4Z]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__bjKaCwlptu]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_one__bjKaCuMy6R]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svgstars_three__bjKaCgmHjh]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two__bjKaCSmpEf]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svgstars_zero__bjKaC8966U]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__lqAJp, {
              [sty.svgstars_five__lqAJpDAe4Z]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__lqAJpwlptu]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_three__lqAJpgmHjh]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two__lqAJpSmpEf]: hasVariant(
                variants,
                "stars",
                "two"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__uYfBu, {
              [sty.svgstars_five__uYfBudAe4Z]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__uYfBUwlptu]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_three__uYfBUgmHjh]: hasVariant(
                variants,
                "stars",
                "three"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg___95PmW, {
              [sty.svgstars_five___95PmWdAe4Z]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four___95PmWwlptu]: hasVariant(
                variants,
                "stars",
                "four"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(hasVariant(variants, "stars", "five") ? true : true) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__h9Tv0, {
              [sty.svgstars_five__h9Tv0DAe4Z]: hasVariant(
                variants,
                "stars",
                "five"
              )
            })}
            role={"img"}
          />
        ) : null}
      </p.Stack>

      {p.renderPlasmicSlot({
        defaultContents: "(45 Review)",
        value: args.numReviews,
        className: classNames(sty.slotTargetNumReviews)
      })}
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRatings__ArgProps,
      internalVariantPropNames: PlasmicRatings__VariantProps
    });

    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings";
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`;
  }
  return func;
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps
  }
);

export default PlasmicRatings;
/* prettier-ignore-end */
